"""
Crop Knowledge Base for AI-Based Crop Rotation Planning System.
Contains comprehensive agronomic metadata including botanical family,
water requirements, cultivation costs, nitrogen fixing/depleting dynamics,
duration, yield, market prices, soil suitability, and pest profiles.
"""

from typing import Dict, List, Any

SOIL_TYPES = [
    "Loamy",
    "Clayey",
    "Sandy",
    "Black Cotton",
    "Alluvial",
    "Red Sandy Loam"
]

CROP_FAMILIES = {
    "Fabaceae": "Legumes (Nitrogen fixers, restorative, breaks pest cycles)",
    "Poaceae": "Grasses & Cereals (High biomass, heavy nitrogen feeders)",
    "Solanaceae": "Nightshades (Heavy nutrient extractors, susceptible to root nematodes/blights)",
    "Brassicaceae": "Crucifers (Biofumigant glucosinolates in root exudates suppress soil pathogens)",
    "Malvaceae": "Mallows (Deep taproot system, breaks hardpan, high resource demand)",
    "Asteraceae": "Composites (Deep rooting, moderate water requirements)",
    "Cucurbitaceae": "Gourds & Melons (Quick growing surface cover, shallow rooting)",
    "Alliaceae": "Alliums (Natural pest repellent properties, sulfur users)"
}

CROPS: Dict[str, Dict[str, Any]] = {
    "chickpea": {
        "id": "chickpea",
        "name": "Chickpea (Bengal Gram)",
        "family": "Fabaceae",
        "category": "Pulse / Legume",
        "water_req_mm": 250,
        "cost_per_acre": 11000,
        "yield_per_acre_quintals": 8.5,
        "market_price_per_quintal": 5440,
        "nitrogen_effect_kg_ha": 38,       # Fixes 38 kg/ha N
        "soil_health_delta": 14,          # +14 to soil index
        "duration_days": 110,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Loamy", "Clayey", "Black Cotton", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Pod Borer"],
        "agronomic_benefit": "Enriches soil with atmospheric nitrogen; excellent preceding crop for wheat/maize."
    },
    "pigeon_pea": {
        "id": "pigeon_pea",
        "name": "Pigeon Pea (Arhar / Tur)",
        "family": "Fabaceae",
        "category": "Pulse / Legume",
        "water_req_mm": 380,
        "cost_per_acre": 12500,
        "yield_per_acre_quintals": 7.5,
        "market_price_per_quintal": 7000,
        "nitrogen_effect_kg_ha": 42,
        "soil_health_delta": 16,
        "duration_days": 150,
        "season_affinity": ["Kharif", "Rainy"],
        "suitable_soils": ["Loamy", "Black Cotton", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Pod Borer", "Wilt"],
        "agronomic_benefit": "Deep root system loosens subsoil and fixes abundant nitrogen."
    },
    "green_gram": {
        "id": "green_gram",
        "name": "Green Gram (Moong)",
        "family": "Fabaceae",
        "category": "Pulse / Legume",
        "water_req_mm": 210,
        "cost_per_acre": 8500,
        "yield_per_acre_quintals": 5.5,
        "market_price_per_quintal": 8550,
        "nitrogen_effect_kg_ha": 30,
        "soil_health_delta": 12,
        "duration_days": 70,
        "season_affinity": ["Zaid", "Summer", "Kharif"],
        "suitable_soils": ["Loamy", "Sandy", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Yellow Mosaic Virus"],
        "agronomic_benefit": "Fast 70-day catch crop that quickly restores depleted soil organic carbon and nitrogen."
    },
    "black_gram": {
        "id": "black_gram",
        "name": "Black Gram (Urad)",
        "family": "Fabaceae",
        "category": "Pulse / Legume",
        "water_req_mm": 230,
        "cost_per_acre": 8800,
        "yield_per_acre_quintals": 5.2,
        "market_price_per_quintal": 6950,
        "nitrogen_effect_kg_ha": 32,
        "soil_health_delta": 12,
        "duration_days": 80,
        "season_affinity": ["Kharif", "Rabi"],
        "suitable_soils": ["Loamy", "Clayey", "Black Cotton", "Alluvial"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Whitefly", "Leaf Crinkle"],
        "agronomic_benefit": "Dense canopy smothers weeds, conserves moisture, and fixes nitrogen."
    },
    "soybean": {
        "id": "soybean",
        "name": "Soybean",
        "family": "Fabaceae",
        "category": "Oilseed / Legume",
        "water_req_mm": 420,
        "cost_per_acre": 13500,
        "yield_per_acre_quintals": 9.5,
        "market_price_per_quintal": 4890,
        "nitrogen_effect_kg_ha": 36,
        "soil_health_delta": 13,
        "duration_days": 105,
        "season_affinity": ["Kharif", "Rainy"],
        "suitable_soils": ["Loamy", "Clayey", "Black Cotton", "Alluvial"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Stem Fly", "Girdle Beetle"],
        "agronomic_benefit": "High protein oilseed with substantial nodulation, replenishing soil nitrogen reserve."
    },
    "groundnut": {
        "id": "groundnut",
        "name": "Groundnut (Peanut)",
        "family": "Fabaceae",
        "category": "Oilseed / Legume",
        "water_req_mm": 460,
        "cost_per_acre": 16000,
        "yield_per_acre_quintals": 11.0,
        "market_price_per_quintal": 6370,
        "nitrogen_effect_kg_ha": 26,
        "soil_health_delta": 10,
        "duration_days": 115,
        "season_affinity": ["Kharif", "Rabi"],
        "suitable_soils": ["Sandy", "Loamy", "Red Sandy Loam", "Alluvial"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Tikka Disease", "Leaf Miner"],
        "agronomic_benefit": "Aerates soil during peg development and contributes residual nitrogen."
    },
    "lentil": {
        "id": "lentil",
        "name": "Lentil (Masoor)",
        "family": "Fabaceae",
        "category": "Pulse / Legume",
        "water_req_mm": 220,
        "cost_per_acre": 9500,
        "yield_per_acre_quintals": 6.5,
        "market_price_per_quintal": 6420,
        "nitrogen_effect_kg_ha": 30,
        "soil_health_delta": 11,
        "duration_days": 105,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Loamy", "Clayey", "Alluvial", "Black Cotton"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Rust", "Aphids"],
        "agronomic_benefit": "Low input cost, excellent cold resilience, and improves soil structure."
    },
    "wheat": {
        "id": "wheat",
        "name": "Wheat",
        "family": "Poaceae",
        "category": "Cereal",
        "water_req_mm": 400,
        "cost_per_acre": 14000,
        "yield_per_acre_quintals": 18.0,
        "market_price_per_quintal": 2275,
        "nitrogen_effect_kg_ha": -40,      # Depletes 40 kg/ha N
        "soil_health_delta": -8,          # -8 to soil index
        "duration_days": 125,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Loamy", "Clayey", "Alluvial", "Black Cotton"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Rust", "Karnal Bunt", "Termites"],
        "agronomic_benefit": "Staple cereal with guaranteed market demand; requires preceding legume for maximum yield."
    },
    "rice": {
        "id": "rice",
        "name": "Paddy (Rice)",
        "family": "Poaceae",
        "category": "Cereal",
        "water_req_mm": 1050,
        "cost_per_acre": 19500,
        "yield_per_acre_quintals": 22.0,
        "market_price_per_quintal": 2300,
        "nitrogen_effect_kg_ha": -52,
        "soil_health_delta": -12,
        "duration_days": 130,
        "season_affinity": ["Kharif", "Rainy"],
        "suitable_soils": ["Clayey", "Loamy", "Alluvial", "Black Cotton"],
        "drought_tolerance": "Low",
        "pest_susceptibility": ["Stem Borer", "Brown Planthopper", "Blast"],
        "agronomic_benefit": "High gross revenue in water-abundant zones; leaves stubble needing microbial decomposition."
    },
    "maize": {
        "id": "maize",
        "name": "Maize (Corn)",
        "family": "Poaceae",
        "category": "Cereal",
        "water_req_mm": 480,
        "cost_per_acre": 13000,
        "yield_per_acre_quintals": 24.0,
        "market_price_per_quintal": 2090,
        "nitrogen_effect_kg_ha": -45,
        "soil_health_delta": -9,
        "duration_days": 105,
        "season_affinity": ["Kharif", "Rabi", "Spring"],
        "suitable_soils": ["Loamy", "Sandy", "Alluvial", "Red Sandy Loam", "Black Cotton"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Fall Armyworm", "Stem Borer"],
        "agronomic_benefit": "High biomass producer and versatile feeder; responsive to balanced soil nutrients."
    },
    "pearl_millet": {
        "id": "pearl_millet",
        "name": "Pearl Millet (Bajra)",
        "family": "Poaceae",
        "category": "Nutri-Cereal / Millet",
        "water_req_mm": 240,
        "cost_per_acre": 8200,
        "yield_per_acre_quintals": 12.0,
        "market_price_per_quintal": 2500,
        "nitrogen_effect_kg_ha": -24,
        "soil_health_delta": -4,
        "duration_days": 85,
        "season_affinity": ["Kharif", "Rainy"],
        "suitable_soils": ["Sandy", "Red Sandy Loam", "Loamy", "Alluvial"],
        "drought_tolerance": "Very High",
        "pest_susceptibility": ["Downy Mildew", "Ergot"],
        "agronomic_benefit": "Extraordinarily climate-resilient; thrives under severe water stress and poor soils."
    },
    "sorghum": {
        "id": "sorghum",
        "name": "Sorghum (Jowar)",
        "family": "Poaceae",
        "category": "Nutri-Cereal / Millet",
        "water_req_mm": 300,
        "cost_per_acre": 8800,
        "yield_per_acre_quintals": 13.0,
        "market_price_per_quintal": 3180,
        "nitrogen_effect_kg_ha": -28,
        "soil_health_delta": -5,
        "duration_days": 100,
        "season_affinity": ["Kharif", "Rabi"],
        "suitable_soils": ["Clayey", "Black Cotton", "Loamy", "Alluvial"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Shoot Fly", "Grain Mold"],
        "agronomic_benefit": "Deep fibrous root system extracts residual nutrients and resists dry spells."
    },
    "barley": {
        "id": "barley",
        "name": "Barley (Jau)",
        "family": "Poaceae",
        "category": "Cereal",
        "water_req_mm": 290,
        "cost_per_acre": 9500,
        "yield_per_acre_quintals": 14.0,
        "market_price_per_quintal": 1850,
        "nitrogen_effect_kg_ha": -30,
        "soil_health_delta": -6,
        "duration_days": 115,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Sandy", "Loamy", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Aphids", "Covered Smut"],
        "agronomic_benefit": "Highly tolerant to salinity and semi-arid conditions; low input cost."
    },
    "tomato": {
        "id": "tomato",
        "name": "Tomato",
        "family": "Solanaceae",
        "category": "Vegetable / Cash Crop",
        "water_req_mm": 520,
        "cost_per_acre": 26000,
        "yield_per_acre_quintals": 110.0,
        "market_price_per_quintal": 1200,
        "nitrogen_effect_kg_ha": -48,
        "soil_health_delta": -10,
        "duration_days": 120,
        "season_affinity": ["Kharif", "Rabi", "Spring"],
        "suitable_soils": ["Loamy", "Sandy", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "Low",
        "pest_susceptibility": ["Early Blight", "Fruit Borer", "Root Knot Nematode"],
        "agronomic_benefit": "Very high gross economic returns; sensitive to continuous Solanaceae cropping."
    },
    "potato": {
        "id": "potato",
        "name": "Potato",
        "family": "Solanaceae",
        "category": "Vegetable / Tuber",
        "water_req_mm": 450,
        "cost_per_acre": 28000,
        "yield_per_acre_quintals": 95.0,
        "market_price_per_quintal": 1150,
        "nitrogen_effect_kg_ha": -50,
        "soil_health_delta": -11,
        "duration_days": 95,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Sandy", "Loamy", "Alluvial"],
        "drought_tolerance": "Low",
        "pest_susceptibility": ["Late Blight", "Tuber Moth"],
        "agronomic_benefit": "High carbohydrate yield; requires loose friable soil, leaves good residual tilth."
    },
    "brinjal": {
        "id": "brinjal",
        "name": "Brinjal (Eggplant)",
        "family": "Solanaceae",
        "category": "Vegetable",
        "water_req_mm": 470,
        "cost_per_acre": 20000,
        "yield_per_acre_quintals": 80.0,
        "market_price_per_quintal": 1300,
        "nitrogen_effect_kg_ha": -42,
        "soil_health_delta": -9,
        "duration_days": 130,
        "season_affinity": ["Kharif", "Rabi"],
        "suitable_soils": ["Loamy", "Clayey", "Black Cotton", "Alluvial"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Shoot and Fruit Borer", "Bacterial Wilt"],
        "agronomic_benefit": "Long harvesting window with steady cash flow for farm households."
    },
    "mustard": {
        "id": "mustard",
        "name": "Mustard (Sarson / Rapeseed)",
        "family": "Brassicaceae",
        "category": "Oilseed",
        "water_req_mm": 270,
        "cost_per_acre": 10500,
        "yield_per_acre_quintals": 7.8,
        "market_price_per_quintal": 5650,
        "nitrogen_effect_kg_ha": -26,
        "soil_health_delta": 4,          # Biofumigation positive effect on soil health!
        "duration_days": 110,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Loamy", "Alluvial", "Sandy", "Clayey"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Aphids", "White Rust"],
        "agronomic_benefit": "Produces glucosinolate root exudates acting as biofumigants, suppressing soil pests."
    },
    "cabbage": {
        "id": "cabbage",
        "name": "Cabbage",
        "family": "Brassicaceae",
        "category": "Vegetable",
        "water_req_mm": 370,
        "cost_per_acre": 17500,
        "yield_per_acre_quintals": 85.0,
        "market_price_per_quintal": 850,
        "nitrogen_effect_kg_ha": -32,
        "soil_health_delta": 2,
        "duration_days": 85,
        "season_affinity": ["Rabi", "Winter"],
        "suitable_soils": ["Loamy", "Clayey", "Alluvial"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Diamondback Moth"],
        "agronomic_benefit": "Excellent rotational crop that breaks cereal disease cycles and improves soil structure."
    },
    "cotton": {
        "id": "cotton",
        "name": "Cotton",
        "family": "Malvaceae",
        "category": "Cash / Fibre Crop",
        "water_req_mm": 650,
        "cost_per_acre": 22000,
        "yield_per_acre_quintals": 8.5,
        "market_price_per_quintal": 7120,
        "nitrogen_effect_kg_ha": -44,
        "soil_health_delta": -8,
        "duration_days": 160,
        "season_affinity": ["Kharif", "Rainy"],
        "suitable_soils": ["Black Cotton", "Clayey", "Loamy", "Alluvial"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Pink Bollworm", "Whitefly"],
        "agronomic_benefit": "Deep taproot breaks hardpans; high commercial value but demands soil resting after harvest."
    },
    "sunflower": {
        "id": "sunflower",
        "name": "Sunflower",
        "family": "Asteraceae",
        "category": "Oilseed",
        "water_req_mm": 350,
        "cost_per_acre": 11500,
        "yield_per_acre_quintals": 7.0,
        "market_price_per_quintal": 6760,
        "nitrogen_effect_kg_ha": -28,
        "soil_health_delta": -3,
        "duration_days": 95,
        "season_affinity": ["Kharif", "Rabi", "Zaid"],
        "suitable_soils": ["Loamy", "Black Cotton", "Clayey", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "High",
        "pest_susceptibility": ["Head Borer", "Alternaria"],
        "agronomic_benefit": "Efficient subsoil moisture scavenger with wide adaptability across seasons."
    },
    "cucumber": {
        "id": "cucumber",
        "name": "Cucumber",
        "family": "Cucurbitaceae",
        "category": "Vegetable",
        "water_req_mm": 310,
        "cost_per_acre": 13000,
        "yield_per_acre_quintals": 48.0,
        "market_price_per_quintal": 1400,
        "nitrogen_effect_kg_ha": -20,
        "soil_health_delta": 3,
        "duration_days": 65,
        "season_affinity": ["Zaid", "Summer", "Kharif"],
        "suitable_soils": ["Sandy", "Loamy", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Fruit Fly", "Downy Mildew"],
        "agronomic_benefit": "Rapid growth cycle, acts as summer green cover, minimizes evaporation losses."
    },
    "onion": {
        "id": "onion",
        "name": "Onion",
        "family": "Alliaceae",
        "category": "Vegetable / Bulb",
        "water_req_mm": 410,
        "cost_per_acre": 23000,
        "yield_per_acre_quintals": 72.0,
        "market_price_per_quintal": 1600,
        "nitrogen_effect_kg_ha": -22,
        "soil_health_delta": 4,          # Natural sulfur & allicin pest deterrence
        "duration_days": 120,
        "season_affinity": ["Rabi", "Kharif"],
        "suitable_soils": ["Loamy", "Alluvial", "Red Sandy Loam"],
        "drought_tolerance": "Medium",
        "pest_susceptibility": ["Thrips", "Purple Blotch"],
        "agronomic_benefit": "Sulfur compounds deter recurring soil nematode pests and fungal spores."
    }
}

PRESET_SCENARIOS = {
    "semi_arid_deccan": {
        "id": "semi_arid_deccan",
        "title": "Semi-Arid Deccan Plateau",
        "description": "Rainfed smallholder facing low water availability and limited budget. Needs drought-resilient legumes and millets.",
        "land_size_acres": 2.0,
        "soil_type": "Black Cotton",
        "water_budget_mm": 900,
        "cost_budget": 70000,
        "seasons_count": 3,
        "initial_soil_health": 55
    },
    "indo_gangetic": {
        "id": "indo_gangetic",
        "title": "Indo-Gangetic Alluvial Plain",
        "description": "Productive alluvial soils seeking to break repetitive cereal monoculture with legumes and biofumigant mustard.",
        "land_size_acres": 3.0,
        "soil_type": "Alluvial",
        "water_budget_mm": 2000,
        "cost_budget": 160000,
        "seasons_count": 4,
        "initial_soil_health": 65
    },
    "commercial_horticulture": {
        "id": "commercial_horticulture",
        "title": "Commercial Diversified Farm",
        "description": "Adequate capital and irrigation, aiming to maximize profit while sustaining soil health via pulse-cereal-vegetable rotation.",
        "land_size_acres": 2.0,
        "soil_type": "Loamy",
        "water_budget_mm": 1500,
        "cost_budget": 120000,
        "seasons_count": 3,
        "initial_soil_health": 70
    },
    "drought_stressed_sandy": {
        "id": "drought_stressed_sandy",
        "title": "Drought-Stressed Rainfed Plot",
        "description": "Coarse sandy soil with strict water limits and vulnerable soil organic carbon. Requires high-resilience planning.",
        "land_size_acres": 1.5,
        "soil_type": "Sandy",
        "water_budget_mm": 800,
        "cost_budget": 50000,
        "seasons_count": 3,
        "initial_soil_health": 48
    }
}


def get_crop(crop_id: str) -> Dict[str, Any]:
    """Retrieve crop by ID."""
    return CROPS.get(crop_id)


def get_crops_for_soil(soil_type: str) -> List[Dict[str, Any]]:
    """Return all crops suitable for a given soil type."""
    return [c for c in CROPS.values() if soil_type in c["suitable_soils"]]
